export const CANVAS_NOT_FOND = 'CANVAS_NOT_FOND';
export const WEB_GL_NOT_SUPPORTED = 'WEB_GL_NOT_SUPPORTED';
export const SHADER_COMPILATION_ERROR = 'SHADER_COMPILATION_ERROR';
export const UNABLE_TO_CREATE_PROGRAM = 'UNABLE_TO_CREATE_PROGRAM';
export const UNABLE_TO_LINK_PROGRAM = 'UNABLE_TO_LINK_PROGRAM';
export const FAILED_TO_CREATE_BUFFER = 'FAILED_TO_CREATE_BUFFER';
export const PRIMITIVE_DOES_NOT_EXIST = 'PRIMITIVE_DOES_NOT_EXIST';
